=== stefanik12/parser-z-xsd-schematu/src/input/schema2.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xsd:element name="library">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="isbn" type="xsd:double"/>
                            <xsd:element name="title">
                                <xsd:complexType>
                                    <xsd:attribute name="lang" type="xsd:string" />
                                    <xsd:attribute name="name" type="xsd:string" />
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="author">
                                <xsd:complexType>
                                    <xsd:all>
                                        <xsd:element name="name" type="xsd:string"/>
                                        <xsd:element name="born"/>
                                        <xsd:element name="dead"/> 
                                    </xsd:all>
                                    <xsd:attribute name="id" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="character" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:all>
                                        <xsd:element name="figure" type="xsd:string"/>
                                        <xsd:element name="qualification" type="xsd:string"/>
                                    </xsd:all>
                                    <xsd:attribute name="id" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element> 
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:string"/>
                        <xsd:attribute name="available" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== stefanik12/parser-z-xsd-schematu/src/input/library.xml
<?xml version="1.0"?>
<library xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation='schema2.xsd'>
    <book id="b0836217462" available="true">
        <isbn>
            836217462
        </isbn>
        <title lang="en" name="Being a Dog Is a Full-Time Job"/>
        <author id="CMS">
            <name>
                Charles M Schulz
            </name>
            <born>
                1922-11-26
            </born>
            <dead>
                2000-02-12
            </dead>
        </author>
        <character id="PP">
            <figure>
                Peppermint Patty
            </figure>
            <qualification>
                bold, brash and tomboyish
            </qualification>
        </character>
        <character id="Snoopy">
            <figure>
                Snoopy
            </figure>
            <qualification>
                extroverted beagle
            </qualification>
        </character>
        <character id="Schroeder">
            <figure>
                Schroeder
            </figure>
            <qualification>
                brought classical music to the Peanuts strip
            </qualification>
        </character>
        <character id="Lucy">
            <figure>
                Lucy
            </figure>
            <qualification>
                bossy, crabby and selfish
            </qualification>
        </character>
    </book>
</library>
